### ISSUE TITLE
Samba and sssd

### ISSUE THREAD

**Issue by hortimech** [mahdi22/linux_joindomain#1]
Hi, it looks like you are using Samba with sssd, are you aware that from Samba 4.8.0 , you cannot use sssd with Samba, it is no longer supported.

**Comment by mahdi22** [comment]
Hi, thank you for your observation. Could you please specify at what level i used Samba with sssd ? because in this ansible role i used Samba and winbind just for RedHat/CentOS release 6. for all other higher release (7 and 8) i used sssd. For Ubuntu from release 16 to 20 and Debian from release 9 to 10 also i used sssd.
I hope that is clear now for you. If not i will happy if you re-explain the issue that you have observed
